version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: always
    networks:
      - default
    volumes:
      - mongo-data:/data/db

  express:
    image: todoback
    ports:
      - "6969:6969"
    depends_on:
      - mongo
    restart: always
    networks:
      - default
volumes:
  mongo-data:
    driver: local
