name: integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: building image with docker
        run: docker build -t todoback .
      - name: pushing image to docker hub
        uses: actions/image-pusher@v2
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
          image-name: $DOCKER_IMAGE_NAME
