name: integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: docker build -t todoback . |
          echo ${{ secrets.MONGODB_URI }}
      - name: tag
        run: docker tag todoback masterbohmid/todoback:latest
      - name: push
        run: docker push masterbohmid/todoback:latest
