name: integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: building image with docker
        run: docker build -t todoback .
      - name: pushing image to docker hub
        uses: docker/build-push-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}
          tag: masterbohmid/todo:latest
