name: integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: building image with docker
        run: docker build -t todoback .
      - name: running image with compose
        run: docker-compose up -d
