name: integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: building image with docker
        run: docker build -t todoback .
      - name: pushing image to docker hub
        run: docker push todoback
